### ISSUE TITLE
Test warrior_specific_features in REDCap 10.5.1

### ISSUE THREAD

**Issue by pbchase** [ctsit/warrior_specific_features#11]
We need to upgrade the WARRIOR REDCap instance to align with the other REDCap instances. This module remains untested in a modern REDCap. Please test this module in REDCap 10.5.1

**Comment by michael-bentz** [comment]
What's the process to properly populate `<PREFIX><DAG_ID>` for the **@SUBJECT-ID** action tag? Creating a **WAR** DAG and adding **Alice Manager** did not work. I also reviewed the corresponding section of the [README](https://github.com/ctsit/warrior_specific_features#subject-id-action-tag).

All other features of the external module have been tested and work in REDCap 10.5.1.

**Comment by pbchase** [comment]
> What's the process to properly populate `<PREFIX><DAG_ID>` for the **@SUBJECT-ID** action tag? Creating a **WAR** DAG and adding **Alice Manager** did not work. I also reviewed the corresponding section of the [README](https://github.com/ctsit/warrior_specific_features#subject-id-action-tag).
> 
> All other features of the external module have been tested and work in REDCap 10.5.1.

I'll hazard a guess the user you were logged in as was not in a DAG. To make sure your test user is in a DAG, follow these steps:

1. Add a normal user, _dan_, to your testing project. make sure he can create and update records.
2. Create at least one DAG in the project
3. Add dan to that dag.
4. Logout
5. login as dan

When Dan creates a record it will be in his DAG. Create a test record on the first form. A subsequent form with a field with the @SUBJECT-ID action tag should now work. 

I'm happy meet on a call to review this if these steps do not work.

**Comment by michael-bentz** [comment]
Thank you. You were right, the user was not in a DAG.

Module is working as expected in REDCap 10.5.1.
